import type { Skill, ExecutionRecord, ExecutionStats, SkillAnalytics, ApprovalRequest, TimeSeriesDataPoint } from './types';

// Mock Skills Data
export const mockSkills: Skill[] = [
  // Data Skills
  {
    id: 'db-query',
    name: 'Database Query',
    description: 'Execute SQL queries against connected databases with query optimization and result caching.',
    category: 'data',
    version: '1.2.0',
    author: 'NexusAI',
    trustScore: 95,
    permissions: ['read:database', 'write:cache'],
    status: 'approved',
    requiredCapabilities: ['database-access'],
    estimatedDuration: 'Fast',
    requiresHumanApproval: false,
    rateLimitPerMinute: 100,
    inputSchema: { query: 'string', database: 'string', params: 'object?' },
    outputSchema: { rows: 'array', columns: 'array', rowCount: 'number' },
  },
  {
    id: 'data-transform',
    name: 'Data Transformer',
    description: 'Transform and reshape data from various formats including JSON, CSV, and XML.',
    category: 'data',
    version: '1.0.5',
    author: 'NexusAI',
    trustScore: 92,
    permissions: ['read:data', 'write:data'],
    status: 'approved',
    requiredCapabilities: ['data-processing'],
    estimatedDuration: 'Medium',
    requiresHumanApproval: false,
    rateLimitPerMinute: 50,
    inputSchema: { data: 'any', format: 'string', operations: 'array' },
    outputSchema: { result: 'any', metadata: 'object' },
  },
  {
    id: 'api-fetch',
    name: 'API Fetcher',
    description: 'Fetch data from RESTful APIs with automatic retry, rate limiting, and response caching.',
    category: 'data',
    version: '1.1.2',
    author: 'NexusAI',
    trustScore: 88,
    permissions: ['read:external-api'],
    status: 'approved',
    requiredCapabilities: ['network-access'],
    estimatedDuration: 'Fast',
    requiresHumanApproval: false,
    rateLimitPerMinute: 60,
    inputSchema: { url: 'string', method: 'string', headers: 'object?' },
    outputSchema: { status: 'number', data: 'any', headers: 'object' },
  },
  // Legal Skills
  {
    id: 'legal-citation',
    name: 'Legal Citation Matcher',
    description: 'Extract and visualize legal citation paths for banking and IT compliance domains.',
    category: 'legal',
    version: '1.0.0',
    author: 'NexusAI',
    trustScore: 98,
    permissions: ['read:knowledge', 'write:citations'],
    status: 'approved',
    requiredCapabilities: ['legal-knowledge'],
    estimatedDuration: 'Medium',
    requiresHumanApproval: false,
    rateLimitPerMinute: 30,
    inputSchema: { query: 'string', domain: 'banking | it' },
    outputSchema: { citations: 'array', paths: 'array' },
  },
  {
    id: 'legal-search',
    name: 'Legal Document Search',
    description: 'Search through legal documents, contracts, and regulatory filings with semantic matching.',
    category: 'legal',
    version: '2.1.0',
    author: 'NexusAI',
    trustScore: 94,
    permissions: ['read:documents', 'read:knowledge'],
    status: 'approved',
    requiredCapabilities: ['document-access'],
    estimatedDuration: 'Medium',
    requiresHumanApproval: true,
    rateLimitPerMinute: 20,
    inputSchema: { query: 'string', filters: 'object?' },
    outputSchema: { results: 'array', highlights: 'array' },
  },
  {
    id: 'contract-analyzer',
    name: 'Contract Analyzer',
    description: 'Analyze contracts for key clauses, risks, obligations, and compliance requirements.',
    category: 'legal',
    version: '1.3.0',
    author: 'NexusAI',
    trustScore: 96,
    permissions: ['read:documents', 'write:annotations'],
    status: 'approved',
    requiredCapabilities: ['document-access', 'legal-knowledge'],
    estimatedDuration: 'Slow',
    requiresHumanApproval: true,
    rateLimitPerMinute: 10,
    inputSchema: { document: 'string', analysisType: 'string' },
    outputSchema: { summary: 'object', risks: 'array', clauses: 'array' },
  },
  // Code Skills
  {
    id: 'code-generator',
    name: 'Code Generator',
    description: 'Generate boilerplate code, API endpoints, and common patterns from specifications.',
    category: 'code',
    version: '2.0.0',
    author: 'NexusAI',
    trustScore: 91,
    permissions: ['read:code', 'write:code'],
    status: 'approved',
    requiredCapabilities: ['code-generation'],
    estimatedDuration: 'Fast',
    requiresHumanApproval: false,
    rateLimitPerMinute: 40,
    inputSchema: { spec: 'object', language: 'string', framework: 'string?' },
    outputSchema: { files: 'array', summary: 'string' },
  },
  {
    id: 'code-review',
    name: 'Code Review Assistant',
    description: 'Perform automated code reviews for security, performance, and best practices.',
    category: 'code',
    version: '1.5.0',
    author: 'NexusAI',
    trustScore: 89,
    permissions: ['read:code'],
    status: 'approved',
    requiredCapabilities: ['code-analysis'],
    estimatedDuration: 'Medium',
    requiresHumanApproval: false,
    rateLimitPerMinute: 25,
    inputSchema: { code: 'string', language: 'string', rules: 'array?' },
    outputSchema: { issues: 'array', score: 'number', suggestions: 'array' },
  },
  {
    id: 'test-generator',
    name: 'Test Generator',
    description: 'Generate comprehensive unit and integration tests for code functions.',
    category: 'code',
    version: '1.2.0',
    author: 'NexusAI',
    trustScore: 87,
    permissions: ['read:code', 'write:code'],
    status: 'pending',
    requiredCapabilities: ['code-analysis', 'test-generation'],
    estimatedDuration: 'Medium',
    requiresHumanApproval: true,
    rateLimitPerMinute: 15,
    inputSchema: { code: 'string', testFramework: 'string', coverage: 'number?' },
    outputSchema: { tests: 'array', coverage: 'number' },
  },
];

// Mock Execution Records
export const mockExecutions: ExecutionRecord[] = [
  {
    id: 'exec-001',
    skillId: 'legal-citation',
    skillName: 'Legal Citation Matcher',
    userId: 'admin',
    params: { query: 'contract breach remedies', domain: 'banking' },
    state: 'running',
    startedAt: new Date(Date.now() - 3200).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 3200).toISOString(), level: 'info', message: 'Starting citation extraction...' },
      { timestamp: new Date(Date.now() - 2800).toISOString(), level: 'info', message: 'Querying legal knowledge base...' },
      { timestamp: new Date(Date.now() - 1500).toISOString(), level: 'info', message: 'Building citation graph...' },
    ],
  },
  {
    id: 'exec-002',
    skillId: 'db-query',
    skillName: 'Database Query',
    userId: 'user1',
    params: { query: 'SELECT * FROM transactions WHERE date > 2024-01-01', database: 'main' },
    state: 'queued',
    startedAt: new Date().toISOString(),
    logs: [],
  },
  {
    id: 'exec-003',
    skillId: 'code-review',
    skillName: 'Code Review Assistant',
    userId: 'user2',
    params: { code: 'async function fetchUser(id) { ... }', language: 'typescript' },
    state: 'completed',
    result: { issues: 3, score: 85, suggestions: ['Add error handling', 'Add caching'] },
    startedAt: new Date(Date.now() - 12100).toISOString(),
    completedAt: new Date(Date.now() - 100).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 12100).toISOString(), level: 'info', message: 'Analyzing code structure...' },
      { timestamp: new Date(Date.now() - 11000).toISOString(), level: 'warn', message: 'Missing try-catch block' },
      { timestamp: new Date(Date.now() - 10000).toISOString(), level: 'info', message: 'Code review complete' },
    ],
  },
  {
    id: 'exec-004',
    skillId: 'data-transform',
    skillName: 'Data Transformer',
    userId: 'user3',
    params: { data: { raw: 'data' }, format: 'json', operations: ['normalize', 'filter'] },
    state: 'failed',
    error: 'Invalid data format: expected object, received string',
    startedAt: new Date(Date.now() - 500).toISOString(),
    completedAt: new Date(Date.now() - 200).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 500).toISOString(), level: 'info', message: 'Starting transformation...' },
      { timestamp: new Date(Date.now() - 300).toISOString(), level: 'error', message: 'Data format mismatch detected' },
      { timestamp: new Date(Date.now() - 200).toISOString(), level: 'error', message: 'Transformation failed' },
    ],
  },
  {
    id: 'exec-005',
    skillId: 'contract-analyzer',
    skillName: 'Contract Analyzer',
    userId: 'user4',
    params: { document: 'supplier_contract.pdf', analysisType: 'full' },
    state: 'completed',
    result: { summary: 'Contract looks standard', risks: [' indemnity clause'], clauses: 12 },
    startedAt: new Date(Date.now() - 45000).toISOString(),
    completedAt: new Date(Date.now() - 30000).toISOString(),
    approvalState: 'approved',
    approvedBy: 'admin',
    logs: [
      { timestamp: new Date(Date.now() - 45000).toISOString(), level: 'info', message: 'Loading contract document...' },
      { timestamp: new Date(Date.now() - 40000).toISOString(), level: 'info', message: 'Extracting clauses...' },
      { timestamp: new Date(Date.now() - 35000).toISOString(), level: 'warn', message: 'Found potential risk clause at line 45' },
      { timestamp: new Date(Date.now() - 30000).toISOString(), level: 'info', message: 'Analysis complete' },
    ],
  },
];

// Mock Execution Stats
export const mockStats: ExecutionStats = {
  totalExecutions: 1247,
  successfulExecutions: 1189,
  failedExecutions: 58,
  averageExecutionTimeMs: 1250,
  pendingApprovals: 3,
  activeExecutions: 1,
};

// Mock Analytics
export const mockAnalytics: SkillAnalytics[] = [
  { skillId: 'db-query', skillName: 'Database Query', totalExecutions: 456, successfulExecutions: 448, failedExecutions: 8, averageExecutionTimeMs: 234, lastExecutedAt: new Date().toISOString(), errorRate: 0.018 },
  { skillId: 'legal-citation', skillName: 'Legal Citation Matcher', totalExecutions: 234, successfulExecutions: 230, failedExecutions: 4, averageExecutionTimeMs: 1850, lastExecutedAt: new Date().toISOString(), errorRate: 0.017 },
  { skillId: 'code-review', skillName: 'Code Review Assistant', totalExecutions: 198, successfulExecutions: 192, failedExecutions: 6, averageExecutionTimeMs: 2100, lastExecutedAt: new Date().toISOString(), errorRate: 0.03 },
  { skillId: 'data-transform', skillName: 'Data Transformer', totalExecutions: 167, successfulExecutions: 158, failedExecutions: 9, averageExecutionTimeMs: 890, lastExecutedAt: new Date().toISOString(), errorRate: 0.054 },
  { skillId: 'contract-analyzer', skillName: 'Contract Analyzer', totalExecutions: 89, successfulExecutions: 87, failedExecutions: 2, averageExecutionTimeMs: 4500, lastExecutedAt: new Date().toISOString(), errorRate: 0.022 },
  { skillId: 'legal-search', skillName: 'Legal Document Search', totalExecutions: 67, successfulExecutions: 65, failedExecutions: 2, averageExecutionTimeMs: 1200, lastExecutedAt: new Date().toISOString(), errorRate: 0.03 },
  { skillId: 'code-generator', skillName: 'Code Generator', totalExecutions: 45, successfulExecutions: 42, failedExecutions: 3, averageExecutionTimeMs: 560, lastExecutedAt: new Date().toISOString(), errorRate: 0.067 },
  { skillId: 'api-fetch', skillName: 'API Fetcher', totalExecutions: 34, successfulExecutions: 34, failedExecutions: 0, averageExecutionTimeMs: 180, lastExecutedAt: new Date().toISOString(), errorRate: 0 },
  { skillId: 'test-generator', skillName: 'Test Generator', totalExecutions: 23, successfulExecutions: 21, failedExecutions: 2, averageExecutionTimeMs: 3400, lastExecutedAt: new Date().toISOString(), errorRate: 0.087 },
];

// Mock Time Series Data
export const mockTimeSeriesData: TimeSeriesDataPoint[] = [
  { timestamp: '2024-01', executions: 89, successes: 82, failures: 7 },
  { timestamp: '2024-02', executions: 112, successes: 105, failures: 7 },
  { timestamp: '2024-03', executions: 145, successes: 138, failures: 7 },
  { timestamp: '2024-04', executions: 178, successes: 170, failures: 8 },
  { timestamp: '2024-05', executions: 195, successes: 186, failures: 9 },
  { timestamp: '2024-06', executions: 210, successes: 201, failures: 9 },
  { timestamp: '2024-07', executions: 234, successes: 224, failures: 10 },
  { timestamp: '2024-08', executions: 256, successes: 245, failures: 11 },
  { timestamp: '2024-09', executions: 289, successes: 278, failures: 11 },
  { timestamp: '2024-10', executions: 312, successes: 301, failures: 11 },
  { timestamp: '2024-11', executions: 345, successes: 333, failures: 12 },
  { timestamp: '2024-12', executions: 378, successes: 366, failures: 12 },
];

// Mock Approval Requests
export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'approval-001',
    skillId: 'test-generator',
    skillName: 'Test Generator',
    userId: 'user1',
    params: { code: 'function processPayment() { ... }', testFramework: 'jest', coverage: 80 },
    requestedAt: new Date(Date.now() - 300000).toISOString(),
    riskLevel: 'medium',
    purpose: 'Generating unit tests for payment processing module',
  },
  {
    id: 'approval-002',
    skillId: 'code-generator',
    skillName: 'Code Generator',
    userId: 'user2',
    params: { spec: { endpoint: '/api/users', methods: ['GET', 'POST'] }, language: 'go' },
    requestedAt: new Date(Date.now() - 180000).toISOString(),
    riskLevel: 'low',
    purpose: 'Generating CRUD API endpoints for user management',
  },
  {
    id: 'approval-003',
    skillId: 'legal-search',
    skillName: 'Legal Document Search',
    userId: 'user3',
    params: { query: 'GDPR compliance requirements', filters: { jurisdiction: 'EU' } },
    requestedAt: new Date(Date.now() - 120000).toISOString(),
    riskLevel: 'low',
    purpose: 'Researching GDPR requirements for product launch',
  },
];

// Category distribution for pie chart
export const categoryDistribution = [
  { name: 'Data', value: 657, color: '#3B82F6' },
  { name: 'Legal', value: 390, color: '#10B981' },
  { name: 'Code', value: 266, color: '#8B5CF6' },
];

// Duration data for bar chart
export const durationData = [
  { name: 'Database Query', avgDuration: 234 },
  { name: 'API Fetcher', avgDuration: 180 },
  { name: 'Code Generator', avgDuration: 560 },
  { name: 'Data Transform', avgDuration: 890 },
  { name: 'Legal Search', avgDuration: 1200 },
  { name: 'Legal Citation', avgDuration: 1850 },
  { name: 'Code Review', avgDuration: 2100 },
  { name: 'Test Generator', avgDuration: 3400 },
  { name: 'Contract Analyzer', avgDuration: 4500 },
];
